services:
  rabbitmq:
    image: "rabbitmq:4.0-management"
    container_name: rabbitmq
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # RabbitMQ broker
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: "postgres:15"
    container_name: postgres1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
